// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hblljnhofvcflilawtkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhibGxqbmhvZnZjZmxpbGF3dGtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MDAyNDgsImV4cCI6MjA3NjM3NjI0OH0.vYAo27VhPxxjuOBdJKpWujnYnFDXZ7MdsuHkD4VHE2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);